-- Add new settings columns to profiles table
ALTER TABLE public.profiles
ADD COLUMN IF NOT EXISTS display_name text,
ADD COLUMN IF NOT EXISTS avatar_url text,
ADD COLUMN IF NOT EXISTS account_private boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS comment_privacy text DEFAULT 'everyone' CHECK (comment_privacy IN ('everyone', 'followers', 'none')),
ADD COLUMN IF NOT EXISTS search_visible boolean DEFAULT true,
ADD COLUMN IF NOT EXISTS language text DEFAULT 'english',
ADD COLUMN IF NOT EXISTS autoplay_videos boolean DEFAULT true,
ADD COLUMN IF NOT EXISTS content_difficulty text DEFAULT 'normal' CHECK (content_difficulty IN ('beginner', 'normal', 'advanced')),
ADD COLUMN IF NOT EXISTS daily_time_goal integer DEFAULT 30,
ADD COLUMN IF NOT EXISTS ai_assistance_level text DEFAULT 'normal' CHECK (ai_assistance_level IN ('simple', 'normal', 'detailed')),
ADD COLUMN IF NOT EXISTS ai_answer_mode text DEFAULT 'text' CHECK (ai_answer_mode IN ('text', 'voice')),
ADD COLUMN IF NOT EXISTS ai_personality text DEFAULT 'friendly' CHECK (ai_personality IN ('friendly', 'formal', 'funny')),
ADD COLUMN IF NOT EXISTS allow_ai_data_usage boolean DEFAULT true,
ADD COLUMN IF NOT EXISTS upload_quality text DEFAULT 'auto' CHECK (upload_quality IN ('hd', 'sd', 'auto')),
ADD COLUMN IF NOT EXISTS notifications_enabled boolean DEFAULT true,
ADD COLUMN IF NOT EXISTS notification_likes boolean DEFAULT true,
ADD COLUMN IF NOT EXISTS notification_comments boolean DEFAULT true,
ADD COLUMN IF NOT EXISTS notification_reminders boolean DEFAULT true,
ADD COLUMN IF NOT EXISTS notification_ai_suggestions boolean DEFAULT true,
ADD COLUMN IF NOT EXISTS text_size text DEFAULT 'medium' CHECK (text_size IN ('small', 'medium', 'large')),
ADD COLUMN IF NOT EXISTS subtitles_enabled boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS dyslexia_font boolean DEFAULT false;